version: '3.9'

services:
  ollama-web:
    build:
      context: ./ollama_front/ollama-web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - ollama-back
    networks:
      - ollama-network

  ollama-back:
    build:
      context: ./ollama_back
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - qdrant
      - ollama-api
    networks:
      - ollama-network  # ✅ 네트워크 추가

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    networks:
      - ollama-network

  ollama-api:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_models:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    networks:
      - ollama-network

networks:
  ollama-network:
    driver: bridge
